//
//  LoginWorker.swift
//  ProductList
//
//  Created by vitalii on 29.11.2020.
//  Copyright © 2020 Vitalii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginWorkerProtocol {
	func clearDatabaseIfNeeded()
	func isLoggedIn() -> Bool
	func sendLogin(uname: String, pw: String, completion: @escaping (Bool, String?) -> ())
	func sendRegister(uname: String, pw: String, completion: @escaping (Bool, String?) -> ())
}


class LoginWorker: LoginWorkerProtocol
{
	var dataProvider: DataProviderProtocol = DataProvider.shared
	
	func isLoggedIn() -> Bool {
		return dataProvider.dataStore.isLoggedIn
	}
	
	func clearDatabaseIfNeeded() {
		self.dataProvider.database.clearIfNeeded()
	}
	
	func sendLogin(uname: String, pw: String, completion: @escaping (Bool, String?)->()){
		dataProvider.sendLogin(uname: uname, pw: pw) { (success, error) in
			completion(success, error)
		}
	}
	
	func sendRegister(uname: String, pw: String, completion: @escaping (Bool, String?) -> ())
	{
		dataProvider.sendRegister(uname: uname, pw: pw) { (success, error) in
			completion(success, error)
		}
	}
}
