//
//  LoginRouter.swift
//  ProductList
//
//  Created by vitalii on 29.11.2020.
//  Copyright © 2020 Vitalii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
    func routeToProducts()
}

protocol LoginDataPassing
{
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
  weak var viewController: LoginView?
  var dataStore: LoginDataStore?
  
  // MARK: Routing

    func routeToProducts(){
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
		DispatchQueue.main.async { [weak self] in
			let destinationVC = storyboard.instantiateViewController(withIdentifier: "ProductsViewController") as! ProductsViewController
			if let vc = self?.viewController {
				self?.navigateToProducts(source: vc, destination: destinationVC)
			}
		}
    }
    
    // MARK: Navigation
    
    func navigateToProducts(source: LoginView, destination: ProductsViewController)
    {
      //source.show(destination, sender: nil)
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    
    func passDataToProducts(source: LoginDataStore, destination: inout ProductsDataStore){
      //destination.name = source.name
    }
}
