//
//  LoginModels.swift
//  ProductList
//
//  Created by vitalii on 29.11.2020.
//  Copyright © 2020 Vitalii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Validator


enum Login{
    enum UIComponents{
        case spacer // spacer
        case uname // for email textfield
        case password // for password textfield
		case error 
        case signInbutton // for sign in button
		case signUpbutton
		case skipButton
        case signInOption // for sign in option label
        case signUpOption // for sign up option label
		case skipOption
    }
    
    
    enum UI{
        struct Request{}
        struct Response{
            var uiComponenets : [UIComponents]?
        }
        
        struct ViewModel{
            var cellConfigs : [(Login.UIComponents, BaseCellConfig)]?
        }
    }
    
    enum Validate{
        struct Request {
            var uname : String?
            var password : String?
        }
        
        struct Response{
            var validationResultUname : ValidationResult?
            var validationResultPassword : ValidationResult?
        }
        
        struct ViewModel{
            var errorMessageForUname : NSAttributedString?
            var errorMessageForPassword : NSAttributedString?
        }
    }
    
    enum SignIn{
        struct Request{}
        struct Response{
			var error: NSAttributedString?
			var signInResult: Bool
		}
        struct ViewModel{
		}
        struct ErrorViewModel{
            var error: NSAttributedString?
        }
    }
	
	enum SignUp{
		struct Request{}
		struct Response{
			var error: NSAttributedString?
			var signUpResult: Bool
		}
		struct ViewModel{
		}
		struct ErrorViewModel{
			var error: NSAttributedString?
		}
	}
	
	enum Skip{
		struct Request{}
		struct Response{}
		struct ViewModel{}
		struct ErrorViewModel{}
	}
    
	enum onLaunch
	{
		struct Request
		{
		}
		struct Response
		{
		}
		struct ViewModel
		{
		}
	}
	
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
}
